### ISSUE TITLE
what is the presumed folder when we execute load_all()

### ISSUE THREAD

**Issue by xvtstephen** [jennybc/foofactors#2]
this in section 2.8. it is not clear what is getwd() and how to avoid loading unwanted stuff. I am working from ESS and have a file play-package.R and execute the 
library(devtools)
library(tidyverse)
library(fs)
load_all("./foofactors/")

and it does not load the foofactors at all. foofactors is a folder just under my workdir and the fbind.R is there. according the load_all help it should load the path provided, but it does not.

**Comment by jennybc** [comment]
Hi @xvtstephen,

This issue doesn't appear to be a bug report or a specific feature request, so it's more suitable for [RStudio Community](https://community.rstudio.com). 

Thanks!
